import type { NextPage } from "next"
import Head from "next/head"

import { Loader, Services, Transactions, Welcome } from "@components"

const HomePage: NextPage = () => {
  return (
    <div className="min-h-screen ">
      <Head>
        <title>Chain Reaction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome />
      <Services />
      <Transactions />
    </div>
  )
}

export default HomePage
