import type { NextPage } from "next"
import Head from "next/head"

import { Navbar, Services, Transactions, Welcome } from "@components"

const HomePage: NextPage = () => {
  return (
    <div className="min-h-screen ">
      <Head>
        <title>Chain Reaction</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="gradient-bg-welcome">
        <Navbar />
        <Welcome />
      </div>
      <Services />
      <Transactions />
    </div>
  )
}

export default HomePage
